
name: Upload to www.tuppi.ovh

on: 
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@v2
      with: 
        submodules: 'recursive'
    # requirements
    - name: requirements
      run: python3 -m pip install -r requirements.txt ; apt-get install -y plantuml
    # publish script
    - name: publish
      run: bash publish.sh

