
name: Upload to www.tuppi.ovh

on: 
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@v2
      with: 
        submodules: 'recursive'
    # requirements
    - name: requirements
      run: python3 -m pip install -r requirements.txt ; sudo apt-get install -y plantuml
    # mkdocs
    - name: mkdocs
      run: mkdir output ; python3 -m mkdocs build -d output
    # publish
    - name: publish
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'output'
        destination-github-username: 'tuppi-ovh'
        destination-repository-name: 'tuppi-ovh.github.io'
        user-email: tuppi-ovh@gmail.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: master
