
name: Upload to www.tuppi.ovh

on: 
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: requirements
      run: python3 -m pip install -r requirements.txt 
    - name: publish
      run: bash publish.sh

